#!/usr/bin/python3
import sys


def factorize(n):
    factors = []
    for i in range(2, n // 2 + 1):
        if n % i == 0:
            factors.append((i, n // i))
    return factors


if __name__ == "__main__":
    if len(sys.argv) != 2:
        print("Usage: python factors.py <file>")
        sys.exit(1)

    input_file = sys.argv[1]

    with open(input_file, 'r') as file:
        numbers = file.read().splitlines()

    for number in numbers:
        num = int(number)
        factor_pairs = factorize(num)
        for pair in factor_pairs:
            print(f"{num}={pair[0]}*{pair[1]}")
